FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY app ./app

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Command to run the worker
CMD ["python", "-m", "app.services.worker.tasks"]